# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

   name: .NET Core CI

   on:
     push:
       branches:
         - main   # Change to your target branch (e.g., 'develop' if using a different branch)
     pull_request:
       branches:
         - main   # Change to your target branch

   jobs:
     build:
       runs-on: ubuntu-latest  # The OS on which the tests will run

       steps:
         # Checkout the repository code
         - name: Checkout code
           uses: actions/checkout@v2

         # Set up .NET SDK version
         - name: Set up .NET
           uses: actions/setup-dotnet@v1
           with:
             dotnet-version: '8.0'  # Specify your .NET SDK version

         # Restore dependencies for the main project
         - name: Restore dependencies
           run: dotnet restore OrderFlowApp

         # Restore dependencies for the test project
         - name: Restore test dependencies
           run: dotnet restore OrderFlowApp.Tests

         # Build the main application
         - name: Build the application
           run: dotnet build OrderFlowApp --configuration Release --no-restore

         # Build the test project
         - name: Build test project
           run: dotnet build OrderFlowgApp.Tests --configuration Release --no-restore

         # Run the automated tests
         - name: Run tests
           run: dotnet test OrderFlowApp.Tests --no-build --verbosity normal
